export { default as Google } from './Google'
export { default as Location } from './Location'
export { default as Facebook } from './Facebook'
export { default as Instagram } from './Instagram'
export { default as Linkedin } from './Linkedin'
export { default as Patreon } from './Patreon'
export { default as Youtube } from './Youtube'
